import { makeStyles, tokens } from "@fluentui/react-components";

export const useAppStyles = makeStyles({
  root: {
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  header: {
    backgroundColor: "transparent",
    color: tokens.colorNeutralForegroundInverted,
    padding: `0 ${tokens.spacingHorizontalXXL}`,
    height: "48px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    position: "absolute",
    top: "0",
    left: "0",
    right: "0",
    zIndex: "10",
  },
  logo: {
    height: "40px",
    filter: `drop-shadow(0 1px 2px ${tokens.colorNeutralShadowAmbient})`,
  },
  toolbar: {
    display: "flex",
    marginLeft: "auto",
  },
  settingsIcon: {
    color: tokens.colorNeutralForegroundInverted,
    cursor: "pointer",
    marginLeft: "auto",
    padding: tokens.spacingVerticalS,
    filter: `drop-shadow(0 1px 2px ${tokens.colorNeutralShadowAmbient})`,
    transitionDuration: tokens.durationNormal,
    transitionProperty: "opacity",
    transitionTimingFunction: tokens.curveEasyEase,
    ":hover": {
      opacity: "0.8",
    },
  },
  avatarContainer: {
    flex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
    position: "relative",
    backgroundImage: "url(/background.png)",
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    padding: 0,
    paddingTop: "48px",
  },
  avatarCanvas: {
    width: "100%",
    height: "calc(100vh - 48px)",
    maxHeight: "calc(100vh - 48px)",
    objectFit: "cover",
    objectPosition: "bottom",
    display: "block",
    "@media (min-width: 768px)": {
      objectFit: "contain",
    },
    "@media (min-width: 1200px)": {
      width: "auto",
      maxWidth: "100vw",
    },
  },
  loadingContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "transparent",
    color: tokens.colorNeutralForegroundInverted,
  },
  startButton: {
    marginTop: tokens.spacingVerticalXXL,
  },
  systemPromptTextarea: {
    minHeight: "200px",
  },
  errorMessage: {
    color: "#ff4444",
  },
});
